### PR TITLE
Updated hook

### PR DESCRIPTION
**Pull request by felipeforte**
Renamed deprecated hook isLoggedIn() to new isRegistered()

### CODE REVIEW

**Comment by felipeforte** [comment]
Related to #39

**Comment by squirrelslair** [comment]
Sorry, I didn't see this, so had already pushed a pull request. I used !isAnon() instead. I wonder if one is better than the other somehow.

**Comment by valerio-bozzolan** [comment]
Thank you for this pull request. I suggest to the maintainer to merge.

This change has backward compatibility, but without this change the Matomo extension is just NOT compatible anymore with recent MediaWiki versions.

https://phabricator.wikimedia.org/T270450

Thanks for merging

**Comment by Seb35** [comment]
Thanks @felipeforte and sorry for the delay.

Without this patch, it triggers an exception "no function User::isLoggedIn()" from 1.38, and User::isRegistered() exists since 1.34 and was backported to 1.31.12.

I have to update extension.json to document this (currently the constraint is MediaWiki >= 1.25.0).

**Comment by bitsofmymind** [comment]
@Seb35 Merci ! I wanted to get Matomo to work on MW 1.40 but you got to it first.

**Pull request merged**
